-- MySQL Script generated by MySQL Workbench
-- Wed Dec 11 17:21:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema AppliJeux
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AppliJeux
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AppliJeux` DEFAULT CHARACTER SET utf8 ;
USE `AppliJeux` ;

-- -----------------------------------------------------
-- Table `AppliJeux`.`Theme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AppliJeux`.`Theme` ;

CREATE TABLE IF NOT EXISTS `AppliJeux`.`Theme` (
  `idTheme` INT NOT NULL,
  `libelle` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTheme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AppliJeux`.`Jeux`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AppliJeux`.`Jeux` ;

CREATE TABLE IF NOT EXISTS `AppliJeux`.`Jeux` (
  `idJuex` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `description` VARCHAR(140) NULL DEFAULT NULL,
  `durrée` INT NOT NULL,
  `nbjmax` INT(2) NOT NULL,
  `nbjmin` INT(2) NOT NULL,
  `Theme_idTheme` INT NOT NULL,
  PRIMARY KEY (`idJuex`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AppliJeux`.`Adherent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AppliJeux`.`Adherent` ;

CREATE TABLE IF NOT EXISTS `AppliJeux`.`Adherent` (
  `idAdherent` INT(4) NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NULL DEFAULT NULL,
  `Message_idMessage` INT NULL,
  `Jeux_idJuex` INT NULL,
  PRIMARY KEY (`idAdherent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AppliJeux`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AppliJeux`.`Message` ;

CREATE TABLE IF NOT EXISTS `AppliJeux`.`Message` (
  `idMessage` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `lu` TINYINT NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `Adherent_idAdherent` INT(4) NOT NULL,
  `Adherent_Message_idMessage` INT NOT NULL,
  PRIMARY KEY (`idMessage`, `Adherent_idAdherent`, `Adherent_Message_idMessage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AppliJeux`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AppliJeux`.`Admin` ;

CREATE TABLE IF NOT EXISTS `AppliJeux`.`Admin` (
  `idAdherent` INT(4) NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(8) NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idAdherent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AppliJeux`.`Seance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AppliJeux`.`Seance` ;

CREATE TABLE IF NOT EXISTS `AppliJeux`.`Seance` (
  `idSeance` INT NOT NULL,
  `date` DATE NOT NULL,
  `heure_fin` DATETIME NOT NULL,
  `heure_debut` DATETIME NOT NULL,
  `Admin_idAdherent` INT(4) NOT NULL,
  PRIMARY KEY (`idSeance`, `Admin_idAdherent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AppliJeux`.`Adherent_has_Seance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AppliJeux`.`Adherent_has_Seance` ;

CREATE TABLE IF NOT EXISTS `AppliJeux`.`Adherent_has_Seance` (
  `Adherent_idAdherent` INT(4) NOT NULL,
  `Adherent_Message_idMessage` INT NOT NULL,
  `Seance_idSeance` INT NULL,
  `Seance_Admin_idAdherent` INT(4) NOT NULL,
  PRIMARY KEY (`Adherent_idAdherent`, `Adherent_Message_idMessage`, `Seance_idSeance`, `Seance_Admin_idAdherent`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
